// <auto-generated/>
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;

namespace SliceSharp.Cli
{
    /// <summary>
    /// Orchestrates loading the solution, resolving the root symbol, building the slice, and exporting.
    /// (Kept minimal because Program.cs already orchestrates. This type is reserved for future split.)
    /// </summary>
    internal sealed class SliceRunner
    {
        // Reserved for potential future refactor into separate library.
    }
}
